### PR TITLE
Changed the suffix of the interface files to .cfg

### PR DESCRIPTION
**Pull request by ntavares**
now respecting the family :) - needed for IPv6 configuration

### CODE REVIEW

**Comment by arBmind** [comment]
Thank you for sticking to it.
But this seems the same as the last pull request. #6
The managed deletion should be changed as well to only touch `*.cfg` files.

**Comment by ntavares** [comment]
My understanding is that the ability to touch or not other files is a plus. I have no need of such a feature, but just including every file '*' is just bad practive, INMO. People might want to keep backups and /not/ use network_manage_devices.

But looking at the code, I think this message has more characters now than that /enhancement/ :-)

**Comment by ntavares** [comment]
I was about to send the patch since it's almost Xmas, but I'm not convinced: I like the idea of being able to use network_manage_devices to keep interfaces.d clean. Too bad if there were backups. If the idea is to preserve backups, then we should perform them ourselves and honor them the proper way. But this would not be a simple "find ... -name *.cfg" anymore.

I'll leave that to you.

-NT

**Comment by arBmind** [comment]
I close this pull request, as no progress was made.

**Pull request closed without merging**
