### PR TITLE
add all the iface options

### PR DESCRIPTION
**Pull request by SoundGoof**

### CODE REVIEW

**Comment by arBmind** [comment]
Thank you for your pull request.

But your changes seem unnecessary
- `post-up` is an alias for `up` 
- and `pre-down` is an alias for `down`.

**Comment by berendt** [comment]
I think it could help to migrate existing configurations to Ansible. This way existing configurations do not have to be changed when using the aliases.

**Comment by arBmind** [comment]
@berendt good point. If config allows it, we may as well.

**Comment by arBmind** [comment]
Can someone please resolve the pull request?

**Pull request closed without merging**
