### PR TITLE
Adding basic testing

### PR DESCRIPTION
**Pull request by trumant**
For conversation on #42 more than anything.

Basic idea would be to add syntax check, run `ansible-lint` and then run a basic playbook to add an additional interface, a bridge and a bond and validate their configuration.

### CODE REVIEW

**Comment by trumant** [comment]
Build 15 is passing on both Trusty and Precise and runs syntax-check, lint and a simple functional test: https://travis-ci.org/trumant/ansible-network-interfaces/builds/181725164

**Comment by arBmind** [comment]
Good work to get us started.

**Comment by arBmind** [comment]
Can you please resolve the merge conflict, to verify that it still passes.
If it does I will be happy to merge this.

**Comment by trumant** [comment]
I think my recent rebase and squash did so.

**Comment by trumant** [comment]
This is the build of the rebased and squashed changes: https://travis-ci.org/trumant/ansible-network-interfaces/builds/181733977

**Comment by trumant** [comment]
And this is the conflict resolved: https://github.com/trumant/ansible-network-interfaces/compare/0aed9e927e2d...86f9425a6f1c#diff-3d2b7487e8f37272aeb6f25599f2734bR22

**Comment by arBmind** [comment]
ok, merged externally. Thanks again!

**Pull request merged**
